export interface CityOption {
  city: string;
  country: string;
  label: string; // "City, Country" for display
}

const RAW: [string, string][] = [
  // Europe
  ["London", "United Kingdom"],
  ["Paris", "France"],
  ["Rome", "Italy"],
  ["Barcelona", "Spain"],
  ["Madrid", "Spain"],
  ["Amsterdam", "Netherlands"],
  ["Berlin", "Germany"],
  ["Munich", "Germany"],
  ["Hamburg", "Germany"],
  ["Vienna", "Austria"],
  ["Prague", "Czech Republic"],
  ["Budapest", "Hungary"],
  ["Warsaw", "Poland"],
  ["Krakow", "Poland"],
  ["Lisbon", "Portugal"],
  ["Porto", "Portugal"],
  ["Athens", "Greece"],
  ["Thessaloniki", "Greece"],
  ["Brussels", "Belgium"],
  ["Bruges", "Belgium"],
  ["Copenhagen", "Denmark"],
  ["Stockholm", "Sweden"],
  ["Oslo", "Norway"],
  ["Helsinki", "Finland"],
  ["Reykjavik", "Iceland"],
  ["Dublin", "Ireland"],
  ["Edinburgh", "United Kingdom"],
  ["Glasgow", "United Kingdom"],
  ["Manchester", "United Kingdom"],
  ["Zurich", "Switzerland"],
  ["Geneva", "Switzerland"],
  ["Bern", "Switzerland"],
  ["Milan", "Italy"],
  ["Venice", "Italy"],
  ["Florence", "Italy"],
  ["Naples", "Italy"],
  ["Bologna", "Italy"],
  ["Palermo", "Italy"],
  ["Turin", "Italy"],
  ["Seville", "Spain"],
  ["Valencia", "Spain"],
  ["Bilbao", "Spain"],
  ["San Sebastián", "Spain"],
  ["Marseille", "France"],
  ["Lyon", "France"],
  ["Nice", "France"],
  ["Bordeaux", "France"],
  ["Toulouse", "France"],
  ["Strasbourg", "France"],
  ["Bucharest", "Romania"],
  ["Sofia", "Bulgaria"],
  ["Belgrade", "Serbia"],
  ["Zagreb", "Croatia"],
  ["Dubrovnik", "Croatia"],
  ["Split", "Croatia"],
  ["Ljubljana", "Slovenia"],
  ["Bratislava", "Slovakia"],
  ["Tallinn", "Estonia"],
  ["Riga", "Latvia"],
  ["Vilnius", "Lithuania"],
  ["Sarajevo", "Bosnia and Herzegovina"],
  ["Podgorica", "Montenegro"],
  ["Tirana", "Albania"],
  ["Skopje", "North Macedonia"],
  ["Valletta", "Malta"],
  ["Nicosia", "Cyprus"],
  ["Luxembourg City", "Luxembourg"],
  ["Monaco", "Monaco"],
  ["Andorra la Vella", "Andorra"],
  ["Minsk", "Belarus"],
  ["Kyiv", "Ukraine"],
  ["Lviv", "Ukraine"],
  ["Odessa", "Ukraine"],
  ["Tbilisi", "Georgia"],
  ["Yerevan", "Armenia"],
  ["Baku", "Azerbaijan"],
  // Asia — East
  ["Tokyo", "Japan"],
  ["Osaka", "Japan"],
  ["Kyoto", "Japan"],
  ["Sapporo", "Japan"],
  ["Fukuoka", "Japan"],
  ["Nagoya", "Japan"],
  ["Seoul", "South Korea"],
  ["Busan", "South Korea"],
  ["Beijing", "China"],
  ["Shanghai", "China"],
  ["Guangzhou", "China"],
  ["Shenzhen", "China"],
  ["Chengdu", "China"],
  ["Xi'an", "China"],
  ["Chongqing", "China"],
  ["Hong Kong", "China"],
  ["Macau", "China"],
  ["Taipei", "Taiwan"],
  ["Tainan", "Taiwan"],
  // Asia — Southeast
  ["Bangkok", "Thailand"],
  ["Chiang Mai", "Thailand"],
  ["Phuket", "Thailand"],
  ["Singapore", "Singapore"],
  ["Kuala Lumpur", "Malaysia"],
  ["Penang", "Malaysia"],
  ["Jakarta", "Indonesia"],
  ["Bali", "Indonesia"],
  ["Yogyakarta", "Indonesia"],
  ["Surabaya", "Indonesia"],
  ["Manila", "Philippines"],
  ["Cebu", "Philippines"],
  ["Ho Chi Minh City", "Vietnam"],
  ["Hanoi", "Vietnam"],
  ["Hoi An", "Vietnam"],
  ["Da Nang", "Vietnam"],
  ["Phnom Penh", "Cambodia"],
  ["Siem Reap", "Cambodia"],
  ["Vientiane", "Laos"],
  ["Luang Prabang", "Laos"],
  ["Yangon", "Myanmar"],
  ["Naypyidaw", "Myanmar"],
  ["Kathmandu", "Nepal"],
  ["Colombo", "Sri Lanka"],
  ["Dhaka", "Bangladesh"],
  // Asia — South
  ["Mumbai", "India"],
  ["Delhi", "India"],
  ["Bangalore", "India"],
  ["Hyderabad", "India"],
  ["Chennai", "India"],
  ["Kolkata", "India"],
  ["Jaipur", "India"],
  ["Ahmedabad", "India"],
  ["Pune", "India"],
  ["Amritsar", "India"],
  ["Varanasi", "India"],
  ["Goa", "India"],
  ["Kochi", "India"],
  ["Karachi", "Pakistan"],
  ["Lahore", "Pakistan"],
  ["Islamabad", "Pakistan"],
  // Asia — Central & West
  ["Istanbul", "Turkey"],
  ["Ankara", "Turkey"],
  ["Izmir", "Turkey"],
  ["Antalya", "Turkey"],
  ["Tehran", "Iran"],
  ["Isfahan", "Iran"],
  ["Shiraz", "Iran"],
  ["Baghdad", "Iraq"],
  ["Beirut", "Lebanon"],
  ["Amman", "Jordan"],
  ["Tel Aviv", "Israel"],
  ["Jerusalem", "Israel"],
  ["Riyadh", "Saudi Arabia"],
  ["Jeddah", "Saudi Arabia"],
  ["Dubai", "United Arab Emirates"],
  ["Abu Dhabi", "United Arab Emirates"],
  ["Doha", "Qatar"],
  ["Manama", "Bahrain"],
  ["Muscat", "Oman"],
  ["Kuwait City", "Kuwait"],
  ["Almaty", "Kazakhstan"],
  ["Nur-Sultan", "Kazakhstan"],
  ["Tashkent", "Uzbekistan"],
  ["Samarkand", "Uzbekistan"],
  ["Kabul", "Afghanistan"],
  // Russia
  ["Moscow", "Russia"],
  ["Saint Petersburg", "Russia"],
  ["Novosibirsk", "Russia"],
  ["Yekaterinburg", "Russia"],
  // Americas — North
  ["New York", "United States"],
  ["Los Angeles", "United States"],
  ["Chicago", "United States"],
  ["Houston", "United States"],
  ["Phoenix", "United States"],
  ["Philadelphia", "United States"],
  ["San Antonio", "United States"],
  ["San Diego", "United States"],
  ["Dallas", "United States"],
  ["San Francisco", "United States"],
  ["Seattle", "United States"],
  ["Denver", "United States"],
  ["Boston", "United States"],
  ["Atlanta", "United States"],
  ["Miami", "United States"],
  ["Nashville", "United States"],
  ["New Orleans", "United States"],
  ["Portland", "United States"],
  ["Las Vegas", "United States"],
  ["Washington DC", "United States"],
  ["Detroit", "United States"],
  ["Minneapolis", "United States"],
  ["Austin", "United States"],
  ["Charlotte", "United States"],
  ["Baltimore", "United States"],
  ["Louisville", "United States"],
  ["Kansas City", "United States"],
  ["Indianapolis", "United States"],
  ["Columbus", "United States"],
  ["Pittsburgh", "United States"],
  ["Memphis", "United States"],
  ["Richmond", "United States"],
  ["Salt Lake City", "United States"],
  ["Albuquerque", "United States"],
  ["Tucson", "United States"],
  ["Honolulu", "United States"],
  ["Anchorage", "United States"],
  ["Toronto", "Canada"],
  ["Montreal", "Canada"],
  ["Vancouver", "Canada"],
  ["Calgary", "Canada"],
  ["Ottawa", "Canada"],
  ["Edmonton", "Canada"],
  ["Winnipeg", "Canada"],
  ["Quebec City", "Canada"],
  ["Mexico City", "Mexico"],
  ["Guadalajara", "Mexico"],
  ["Monterrey", "Mexico"],
  ["Cancún", "Mexico"],
  ["Oaxaca", "Mexico"],
  ["Puebla", "Mexico"],
  ["Mérida", "Mexico"],
  // Americas — Caribbean
  ["Havana", "Cuba"],
  ["San Juan", "Puerto Rico"],
  ["Santo Domingo", "Dominican Republic"],
  ["Kingston", "Jamaica"],
  ["Port-au-Prince", "Haiti"],
  ["Nassau", "Bahamas"],
  ["Bridgetown", "Barbados"],
  ["Port of Spain", "Trinidad and Tobago"],
  // Americas — Central
  ["Guatemala City", "Guatemala"],
  ["San José", "Costa Rica"],
  ["Panama City", "Panama"],
  ["Tegucigalpa", "Honduras"],
  ["Managua", "Nicaragua"],
  ["San Salvador", "El Salvador"],
  ["Belize City", "Belize"],
  // Americas — South
  ["São Paulo", "Brazil"],
  ["Rio de Janeiro", "Brazil"],
  ["Brasília", "Brazil"],
  ["Salvador", "Brazil"],
  ["Recife", "Brazil"],
  ["Fortaleza", "Brazil"],
  ["Curitiba", "Brazil"],
  ["Porto Alegre", "Brazil"],
  ["Buenos Aires", "Argentina"],
  ["Córdoba", "Argentina"],
  ["Rosario", "Argentina"],
  ["Mendoza", "Argentina"],
  ["Lima", "Peru"],
  ["Cusco", "Peru"],
  ["Bogotá", "Colombia"],
  ["Medellín", "Colombia"],
  ["Cartagena", "Colombia"],
  ["Cali", "Colombia"],
  ["Santiago", "Chile"],
  ["Valparaíso", "Chile"],
  ["Caracas", "Venezuela"],
  ["Quito", "Ecuador"],
  ["Guayaquil", "Ecuador"],
  ["La Paz", "Bolivia"],
  ["Santa Cruz", "Bolivia"],
  ["Asunción", "Paraguay"],
  ["Montevideo", "Uruguay"],
  ["Georgetown", "Guyana"],
  ["Paramaribo", "Suriname"],
  // Africa — North
  ["Cairo", "Egypt"],
  ["Alexandria", "Egypt"],
  ["Casablanca", "Morocco"],
  ["Marrakech", "Morocco"],
  ["Fes", "Morocco"],
  ["Tangier", "Morocco"],
  ["Tunis", "Tunisia"],
  ["Algiers", "Algeria"],
  ["Tripoli", "Libya"],
  ["Khartoum", "Sudan"],
  // Africa — West
  ["Lagos", "Nigeria"],
  ["Abuja", "Nigeria"],
  ["Ibadan", "Nigeria"],
  ["Kano", "Nigeria"],
  ["Accra", "Ghana"],
  ["Kumasi", "Ghana"],
  ["Dakar", "Senegal"],
  ["Abidjan", "Côte d'Ivoire"],
  ["Bamako", "Mali"],
  ["Conakry", "Guinea"],
  ["Ouagadougou", "Burkina Faso"],
  ["Lomé", "Togo"],
  ["Cotonou", "Benin"],
  ["Freetown", "Sierra Leone"],
  ["Monrovia", "Liberia"],
  ["Bissau", "Guinea-Bissau"],
  // Africa — East
  ["Nairobi", "Kenya"],
  ["Mombasa", "Kenya"],
  ["Addis Ababa", "Ethiopia"],
  ["Dar es Salaam", "Tanzania"],
  ["Zanzibar City", "Tanzania"],
  ["Kampala", "Uganda"],
  ["Kigali", "Rwanda"],
  ["Bujumbura", "Burundi"],
  ["Djibouti City", "Djibouti"],
  ["Mogadishu", "Somalia"],
  ["Asmara", "Eritrea"],
  // Africa — Southern
  ["Johannesburg", "South Africa"],
  ["Cape Town", "South Africa"],
  ["Durban", "South Africa"],
  ["Pretoria", "South Africa"],
  ["Maputo", "Mozambique"],
  ["Harare", "Zimbabwe"],
  ["Lusaka", "Zambia"],
  ["Lilongwe", "Malawi"],
  ["Gaborone", "Botswana"],
  ["Windhoek", "Namibia"],
  ["Maseru", "Lesotho"],
  ["Mbabane", "Eswatini"],
  ["Antananarivo", "Madagascar"],
  ["Port Louis", "Mauritius"],
  // Africa — Central
  ["Kinshasa", "Democratic Republic of the Congo"],
  ["Brazzaville", "Republic of the Congo"],
  ["Yaoundé", "Cameroon"],
  ["Douala", "Cameroon"],
  ["Libreville", "Gabon"],
  ["Malabo", "Equatorial Guinea"],
  // Oceania
  ["Sydney", "Australia"],
  ["Melbourne", "Australia"],
  ["Brisbane", "Australia"],
  ["Perth", "Australia"],
  ["Adelaide", "Australia"],
  ["Auckland", "New Zealand"],
  ["Wellington", "New Zealand"],
  ["Christchurch", "New Zealand"],
  ["Suva", "Fiji"],
  ["Port Moresby", "Papua New Guinea"],
  ["Noumea", "New Caledonia"],
  ["Papeete", "French Polynesia"],
];

export const CITIES: CityOption[] = RAW.map(([city, country]) => ({
  city,
  country,
  label: `${city}, ${country}`,
}));

export function searchCities(query: string, limit = 8): CityOption[] {
  if (!query.trim()) return [];
  const q = query.toLowerCase();
  const exact: CityOption[] = [];
  const starts: CityOption[] = [];
  const contains: CityOption[] = [];
  for (const c of CITIES) {
    const lc = c.city.toLowerCase();
    const ll = c.label.toLowerCase();
    if (lc === q) { exact.push(c); continue; }
    if (lc.startsWith(q)) { starts.push(c); continue; }
    if (ll.includes(q)) contains.push(c);
  }
  return [...exact, ...starts, ...contains].slice(0, limit);
}
